"""add daily records and sales

Revision ID: 56c8f76d43a2
Revises: e98178afe573
Create Date: 2026-10-09 16:18:56.188613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c8f76d43a2'
down_revision: Union[str, Sequence[str], None] = 'e98178afe573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_records_date'), 'daily_records', ['date'], unique=True)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_record_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['daily_record_id'], ['daily_records.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_items_daily_record_id'), 'sale_items', ['daily_record_id'], unique=False)
    op.create_index(op.f('ix_sale_items_product_id'), 'sale_items', ['product_id'], unique=False)
    op.create_table('sale_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_allocations_batch_id'), 'sale_allocations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_sale_allocations_sale_item_id'), 'sale_allocations', ['sale_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_allocations_sale_item_id'), table_name='sale_allocations')
    op.drop_index(op.f('ix_sale_allocations_batch_id'), table_name='sale_allocations')
    op.drop_table('sale_allocations')
    op.drop_index(op.f('ix_sale_items_product_id'), table_name='sale_items')
    op.drop_index(op.f('ix_sale_items_daily_record_id'), table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_daily_records_date'), table_name='daily_records')
    op.drop_table('daily_records')
    # ### end Alembic commands ###
